TEMP: update telemetry, quicwrapper, and unbounded version
This points to unmerged PRs:
quicwrapper: jovis/2035-support-singbox-pr
unbounded: jovis/2035-support-singbox-pr

And this one updates to latest main:
telemetry: current main

Also use github.com/sagernet/sing instead of lantern's because of building with these tags will fail:
❯ go build -tags with_utls,with_quic

.../global/pkg/mod/github.com/getlantern/sing-box-minimal@v1.11.12-0.20250616155750-74188abad925/route/route.go:527:39: undefined: M.IsDomainName
.../global/pkg/mod/github.com/getlantern/sing-box-minimal@v1.11.12-0.20250616155750-74188abad925/route/route.go:625:41: undefined: M.IsDomainName